---
# yamllint configuration for E-Waste Workshop

extends: default

rules:
  line-length:
    max: 120
    level: warning
  
  indentation:
    spaces: 2
    indent-sequences: true
  
  comments:
    min-spaces-from-content: 1
  
  document-start:
    present: false
  
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  
  brackets:
    max-spaces-inside: 0
  
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
